// File: main.js
"use strict";

/* Simple incremental game: robust save/load, UI updates, and autosave.
   - Rust Collectors now require Magnet Carts ONLY (no Scrap) and consume them.
   - Persists rustCollector and supports migration from old saves.
   - Clean UI updates and button enable/disable logic based on requirements.
*/

/* =========================
   Constants and Config
   ========================= */
const STORAGE_KEY = "save";                // localStorage key
const SAVE_VERSION = 4;                    // current save schema version

// Magnet Cart: costs Scrap and grows exponentially
const BASE_CART_COST = 10;                 // base Scrap cost for first Magnet Cart
const CART_GROWTH = 1.1;                   // exponential cost growth factor

// Rust Collector: costs Magnet Carts (no Scrap) and grows with count
// NOTE: Aligned with HTML default display; first Rust Collector requires 1 Magnet Cart.
const BASE_COLLECTOR_CART_COST = 5;        // Magnet Carts needed for first Rust Collector
const COLLECTOR_CART_GROWTH = 1.2;         // growth factor for Magnet Cart requirement

// Production and timing
const MAGNET_CART_RATE = 1;                // scrap/sec per Magnet Cart
const RUST_COLLECTOR_RATE = 5;             // scrap/sec per Rust Collector
const TICK_MS = 1000;                      // game tick interval (ms)
const AUTOSAVE_MS = 15000;                 // autosave interval (ms)

/* =========================
   Game State (globals)
   ========================= */
let scrap = 0;
let magnetCart = 0;
let rustCollector = 0;

/* =========================
   Utility Functions
   ========================= */

/**
 * Returns a clamped rounded integer for display.
 * Guards against NaN and negative values.
 */
function prettify(input) {
  const n = Number(input);
  if (!Number.isFinite(n) || n < 0) return 0;
  return Math.round(n);
}

/**
 * Computes the Scrap cost of the next Magnet Cart based on current count.
 */
function getCartCost(count) {
  return Math.floor(BASE_CART_COST * Math.pow(CART_GROWTH, count));
}

/**
 * Computes the Magnet Cart requirement for the next Rust Collector.
 * Uses ceil so growth reflects in integer steps.
 */
function getCollectorCartCost(count) {
  return Math.max(1, Math.ceil(BASE_COLLECTOR_CART_COST * Math.pow(COLLECTOR_CART_GROWTH, count)));
}

/**
 * Computes total scraps per second generated by Magnet Carts.
 */
function getCartSps(count) {
  return count * MAGNET_CART_RATE;
}

/**
 * Computes total scraps per second generated by Rust Collectors.
 */
function getCollectorSps(count) {
  return count * RUST_COLLECTOR_RATE;
}

/**
 * Updates all relevant UI elements and buy button states.
 */
function updateUI() {
  // Value labels
  const scrapEl = document.getElementById("scrap");
  const cartEl = document.getElementById("magnetCart");
  const costEl = document.getElementById("cartCost");
  const collectorEl = document.getElementById("rustCollector");
  const collectorCostEl = document.getElementById("collectorCost");

  // Per-second labels
  const cartSpsEl = document.getElementById("magnetCartSps");
  const collectorSpsEl = document.getElementById("rustCollectorSps");

  if (scrapEl) scrapEl.textContent = String(prettify(scrap));
  if (cartEl) cartEl.textContent = String(prettify(magnetCart));
  if (costEl) costEl.textContent = String(prettify(getCartCost(magnetCart)));
  if (collectorEl) collectorEl.textContent = String(prettify(rustCollector));
  if (collectorCostEl) collectorCostEl.textContent = String(prettify(getCollectorCartCost(rustCollector)));

  // Update per-second displays (totals per generator type)
  if (cartSpsEl) cartSpsEl.textContent = String(prettify(getCartSps(magnetCart)));
  if (collectorSpsEl) collectorSpsEl.textContent = String(prettify(getCollectorSps(rustCollector)));

  // Button enable/disable logic
  const cartBtn = document.getElementById("magnetCartBuy");
  const collectorBtn = document.getElementById("rustCollectorBuy");

  if (cartBtn) {
    cartBtn.disabled = scrap < getCartCost(magnetCart);
    cartBtn.title = cartBtn.disabled
      ? `Requires ${getCartCost(magnetCart)} Scrap`
      : "Create Magnet Cart";
  }

  if (collectorBtn) {
    const reqCarts = getCollectorCartCost(rustCollector);
    const hasCartReq = magnetCart >= reqCarts;
    collectorBtn.disabled = !hasCartReq;
    collectorBtn.title = hasCartReq
      ? `Consumes ${reqCarts} Magnet Carts`
      : `Requires ${reqCarts} Magnet Carts`;
  }
}

/* =========================
   Persistence
   ========================= */

/**
 * Saves the game state to localStorage.
 */
function save() {
  const data = {
    version: SAVE_VERSION,
    scrap,
    magnetCart,
    rustCollector
  };
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  } catch (_) {
    // Ignore quota or serialization errors
  }
}

/**
 * Loads the game state from localStorage, migrating old saves if needed.
 */
function load() {
  let raw = null;
  try {
    raw = localStorage.getItem(STORAGE_KEY);
  } catch (_) {
    updateUI();
    return;
  }

  if (raw == null) {
    updateUI();
    return;
  }

  let savegame;
  try {
    savegame = JSON.parse(raw);
  } catch (_) {
    try { localStorage.removeItem(STORAGE_KEY); } catch (_) {}
    updateUI();
    return;
  }

  // Migrate legacy saves (no version)
  if (savegame.version === undefined) {
    savegame.scrap = Number(savegame.tests) || 0;
    savegame.magnetCart = Number(savegame.testers) || 0;
    savegame.rustCollector = Number(savegame.rustCollector) || 0;
    savegame.version = 2;
  }

  // Ensure rustCollector exists in older versions
  if (savegame.version < 3) {
    savegame.rustCollector = Number(savegame.rustCollector) || 0;
    savegame.version = 3;
  }

  // Finalize migration to current version
  if (savegame.version < SAVE_VERSION) {
    savegame.version = SAVE_VERSION;
    try { localStorage.setItem(STORAGE_KEY, JSON.stringify(savegame)); } catch (_) {}
  }

  // Apply loaded values with sanitization
  scrap = Math.max(0, Math.floor(Number(savegame.scrap) || 0));
  magnetCart = Math.max(0, Math.floor(Number(savegame.magnetCart) || 0));
  rustCollector = Math.max(0, Math.floor(Number(savegame.rustCollector) || 0));

  updateUI();
}

/**
 * Deletes the save and reloads the page.
 */
function deleteSave() {
  try { localStorage.removeItem(STORAGE_KEY); } catch (_) {}
  location.reload();
}

/* =========================
   Game Actions
   ========================= */

/**
 * Adds scrap based on the provided number.
 */
function gatherScrap(number) {
  const inc = Number(number) || 0;
  scrap = Math.max(0, scrap + inc);
  updateUI();
}

/**
 * Attempts to purchase a Magnet Cart if the player can afford it (Scrap cost).
 */
function buyCart() {
  const cost = getCartCost(magnetCart);
  if (scrap >= cost) {
    magnetCart += 1;
    scrap -= cost;
    updateUI();
    save();
  }
}

/**
 * Attempts to build a Rust Collector.
 * Requirement: Magnet Carts only (consumed), no Scrap required.
 */
function buyCollector() {
  const cartCost = getCollectorCartCost(rustCollector);
  if (magnetCart >= cartCost) {
    magnetCart -= cartCost;     // consume required Magnet Carts
    rustCollector += 1;         // add one Rust Collector
    updateUI();
    save();
  }
}

/* =========================
   Loops and Event Hooks
   ========================= */

// Game tick: generates scrap per second from both sources
const tickHandle = setInterval(function () {
  const inc = getCartSps(magnetCart) + getCollectorSps(rustCollector);
  if (inc > 0) gatherScrap(inc);
}, TICK_MS);

// Autosave at an interval
const autosaveHandle = setInterval(function () {
  save();
}, AUTOSAVE_MS);

// Load when the DOM is ready so elements exist for UI updates
document.addEventListener("DOMContentLoaded", function () {
  load();
  updateUI();
});

// Save on page exit/navigation
window.addEventListener("beforeunload", function () {
  save();
});

// Expose functions for inline HTML event handlers
window.gatherScrap = gatherScrap;
window.buyCart = buyCart;
window.buyCollector = buyCollector;
window.save = save;
window.deleteSave = deleteSave;